apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: daily-weather-plugin
  description: A Backstage plugin that fetches and displays real-time weather information using the Weatherstack API. It includes a secure backend proxy configuration.
  annotations:
    github.com/project-slug: Infosys/daily-weather-plugin
    backstage.io/techdocs-ref: dir:.
spec:
  type: plugin
  lifecycle: experimental
  owner: group:admin-group
  ownedBy: [group:admin-group, group:dev-group]
